### ISSUE TITLE
`Bumblebee.Diffusion.VaeKl` could use a public `sample` method

### ISSUE THREAD

**Issue by hanrelan** [elixir-nx/bumblebee#129]
When using Stable Diffusion to create an image to image model, the process is:
Image -> VAE encoder -> Posterior -> Sample from posterior to get latent -> Add noise to latent etc. 

Right now there's no public method to sample from the posterior that the VAE encoder outputs. It's not hard to write but would be nice to have given it's probably a common thing to do.

Side note - I'm probably wrong about this but is this correct? https://github.com/elixir-nx/bumblebee/blob/main/lib/bumblebee/diffusion/vae_kl.ex#L414

Shouldn't this be:
```
    posterior.std
    |> Axon.multiply(z)
    |> Axon.add(posterior.mean)
  end
```
so that the mean isn't also being multiplied by `z`

**Comment by jonatanklosko** [comment]
@hanrelan good catch with the operation order! I didn't came up, because we actually never use sampling in text-to-image Stable Diffusion. Adjusted in b139b845c797c7ddff7ba715b33d1768d3392a7b.

As for adding public `sample`, I would probably wait until we need it in Bumblebee, that is until we add text-to-image or similar.

**Comment by josevalim** [comment]
If there is a use case, let us know and we will gladly reopen.
